/* abstract-tile-object.c generated by valac 0.10.4, the Vala compiler
 * generated from abstract-tile-object.vala, do not modify */

/*
 * Copyright (C) 2010 Michal Hruby <michal.mhr@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA.
 *
 * Authored by Michal Hruby <michal.mhr@gmail.com>
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>
#include <gdk-pixbuf/gdk-pixdata.h>


#define UI_WIDGETS_TYPE_ABSTRACT_TILE_OBJECT (ui_widgets_abstract_tile_object_get_type ())
#define UI_WIDGETS_ABSTRACT_TILE_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), UI_WIDGETS_TYPE_ABSTRACT_TILE_OBJECT, UIWidgetsAbstractTileObject))
#define UI_WIDGETS_ABSTRACT_TILE_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), UI_WIDGETS_TYPE_ABSTRACT_TILE_OBJECT, UIWidgetsAbstractTileObjectClass))
#define UI_WIDGETS_IS_ABSTRACT_TILE_OBJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), UI_WIDGETS_TYPE_ABSTRACT_TILE_OBJECT))
#define UI_WIDGETS_IS_ABSTRACT_TILE_OBJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), UI_WIDGETS_TYPE_ABSTRACT_TILE_OBJECT))
#define UI_WIDGETS_ABSTRACT_TILE_OBJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), UI_WIDGETS_TYPE_ABSTRACT_TILE_OBJECT, UIWidgetsAbstractTileObjectClass))

typedef struct _UIWidgetsAbstractTileObject UIWidgetsAbstractTileObject;
typedef struct _UIWidgetsAbstractTileObjectClass UIWidgetsAbstractTileObjectClass;
typedef struct _UIWidgetsAbstractTileObjectPrivate UIWidgetsAbstractTileObjectPrivate;
#define __g_list_free_g_object_unref0(var) ((var == NULL) ? NULL : (var = (_g_list_free_g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _UIWidgetsAbstractTileObject {
	GObject parent_instance;
	UIWidgetsAbstractTileObjectPrivate * priv;
};

struct _UIWidgetsAbstractTileObjectClass {
	GObjectClass parent_class;
	void (*active_changed) (UIWidgetsAbstractTileObject* self);
};

struct _UIWidgetsAbstractTileObjectPrivate {
	GList* extra_buttons;
	char* _icon;
	GdkPixbuf* _force_pixbuf;
	char* _name;
	char* _description;
	char* _subdesc_title;
	char* _subdesc_text;
	gboolean _show_action_button;
	gboolean _enabled;
	char* _add_button_stock;
	char* _remove_button_stock;
	char* _add_button_tooltip;
	char* _remove_button_tooltip;
};


static gpointer ui_widgets_abstract_tile_object_parent_class = NULL;

GType ui_widgets_abstract_tile_object_get_type (void) G_GNUC_CONST;
#define UI_WIDGETS_ABSTRACT_TILE_OBJECT_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), UI_WIDGETS_TYPE_ABSTRACT_TILE_OBJECT, UIWidgetsAbstractTileObjectPrivate))
enum  {
	UI_WIDGETS_ABSTRACT_TILE_OBJECT_DUMMY_PROPERTY,
	UI_WIDGETS_ABSTRACT_TILE_OBJECT_ICON,
	UI_WIDGETS_ABSTRACT_TILE_OBJECT_FORCE_PIXBUF,
	UI_WIDGETS_ABSTRACT_TILE_OBJECT_NAME,
	UI_WIDGETS_ABSTRACT_TILE_OBJECT_DESCRIPTION,
	UI_WIDGETS_ABSTRACT_TILE_OBJECT_SUB_DESCRIPTION_TITLE,
	UI_WIDGETS_ABSTRACT_TILE_OBJECT_SUB_DESCRIPTION_TEXT,
	UI_WIDGETS_ABSTRACT_TILE_OBJECT_SHOW_ACTION_BUTTON,
	UI_WIDGETS_ABSTRACT_TILE_OBJECT_ENABLED,
	UI_WIDGETS_ABSTRACT_TILE_OBJECT_ADD_BUTTON_STOCK,
	UI_WIDGETS_ABSTRACT_TILE_OBJECT_REMOVE_BUTTON_STOCK,
	UI_WIDGETS_ABSTRACT_TILE_OBJECT_ADD_BUTTON_TOOLTIP,
	UI_WIDGETS_ABSTRACT_TILE_OBJECT_REMOVE_BUTTON_TOOLTIP
};
static void _g_list_free_g_object_unref (GList* self);
GList* ui_widgets_abstract_tile_object_get_extra_buttons (UIWidgetsAbstractTileObject* self);
void ui_widgets_abstract_tile_object_add_user_button (UIWidgetsAbstractTileObject* self, GtkButton* button);
void ui_widgets_abstract_tile_object_remove_user_button (UIWidgetsAbstractTileObject* self, GtkButton* button);
UIWidgetsAbstractTileObject* ui_widgets_abstract_tile_object_construct (GType object_type);
const char* ui_widgets_abstract_tile_object_get_icon (UIWidgetsAbstractTileObject* self);
void ui_widgets_abstract_tile_object_set_icon (UIWidgetsAbstractTileObject* self, const char* value);
GdkPixbuf* ui_widgets_abstract_tile_object_get_force_pixbuf (UIWidgetsAbstractTileObject* self);
void ui_widgets_abstract_tile_object_set_force_pixbuf (UIWidgetsAbstractTileObject* self, GdkPixbuf* value);
const char* ui_widgets_abstract_tile_object_get_name (UIWidgetsAbstractTileObject* self);
void ui_widgets_abstract_tile_object_set_name (UIWidgetsAbstractTileObject* self, const char* value);
const char* ui_widgets_abstract_tile_object_get_description (UIWidgetsAbstractTileObject* self);
void ui_widgets_abstract_tile_object_set_description (UIWidgetsAbstractTileObject* self, const char* value);
const char* ui_widgets_abstract_tile_object_get_sub_description_title (UIWidgetsAbstractTileObject* self);
void ui_widgets_abstract_tile_object_set_sub_description_title (UIWidgetsAbstractTileObject* self, const char* value);
const char* ui_widgets_abstract_tile_object_get_sub_description_text (UIWidgetsAbstractTileObject* self);
void ui_widgets_abstract_tile_object_set_sub_description_text (UIWidgetsAbstractTileObject* self, const char* value);
gboolean ui_widgets_abstract_tile_object_get_show_action_button (UIWidgetsAbstractTileObject* self);
void ui_widgets_abstract_tile_object_set_show_action_button (UIWidgetsAbstractTileObject* self, gboolean value);
gboolean ui_widgets_abstract_tile_object_get_enabled (UIWidgetsAbstractTileObject* self);
void ui_widgets_abstract_tile_object_set_enabled (UIWidgetsAbstractTileObject* self, gboolean value);
const char* ui_widgets_abstract_tile_object_get_add_button_stock (UIWidgetsAbstractTileObject* self);
void ui_widgets_abstract_tile_object_set_add_button_stock (UIWidgetsAbstractTileObject* self, const char* value);
const char* ui_widgets_abstract_tile_object_get_remove_button_stock (UIWidgetsAbstractTileObject* self);
void ui_widgets_abstract_tile_object_set_remove_button_stock (UIWidgetsAbstractTileObject* self, const char* value);
const char* ui_widgets_abstract_tile_object_get_add_button_tooltip (UIWidgetsAbstractTileObject* self);
void ui_widgets_abstract_tile_object_set_add_button_tooltip (UIWidgetsAbstractTileObject* self, const char* value);
const char* ui_widgets_abstract_tile_object_get_remove_button_tooltip (UIWidgetsAbstractTileObject* self);
void ui_widgets_abstract_tile_object_set_remove_button_tooltip (UIWidgetsAbstractTileObject* self, const char* value);
void ui_widgets_abstract_tile_object_active_changed (UIWidgetsAbstractTileObject* self);
static void ui_widgets_abstract_tile_object_real_active_changed (UIWidgetsAbstractTileObject* self);
static void ui_widgets_abstract_tile_object_finalize (GObject* obj);
static void ui_widgets_abstract_tile_object_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void ui_widgets_abstract_tile_object_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static int _vala_strcmp0 (const char * str1, const char * str2);



static void _g_list_free_g_object_unref (GList* self) {
	g_list_foreach (self, (GFunc) g_object_unref, NULL);
	g_list_free (self);
}


GList* ui_widgets_abstract_tile_object_get_extra_buttons (UIWidgetsAbstractTileObject* self) {
	GList* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = g_list_copy (self->priv->extra_buttons);
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void ui_widgets_abstract_tile_object_add_user_button (UIWidgetsAbstractTileObject* self, GtkButton* button) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (button != NULL);
	if (g_list_find (self->priv->extra_buttons, button) == NULL) {
		self->priv->extra_buttons = g_list_append (self->priv->extra_buttons, _g_object_ref0 (button));
		g_signal_emit_by_name (self, "buttons-updated");
	}
}


void ui_widgets_abstract_tile_object_remove_user_button (UIWidgetsAbstractTileObject* self, GtkButton* button) {
	g_return_if_fail (self != NULL);
	g_return_if_fail (button != NULL);
	if (g_list_find (self->priv->extra_buttons, button) != NULL) {
		self->priv->extra_buttons = g_list_remove (self->priv->extra_buttons, button);
		g_signal_emit_by_name (self, "buttons-updated");
	}
}


UIWidgetsAbstractTileObject* ui_widgets_abstract_tile_object_construct (GType object_type) {
	UIWidgetsAbstractTileObject * self = NULL;
	self = (UIWidgetsAbstractTileObject*) g_object_new (object_type, NULL);
	return self;
}


const char* ui_widgets_abstract_tile_object_get_icon (UIWidgetsAbstractTileObject* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	if (self->priv->_icon == NULL) {
		char* _tmp0_;
		self->priv->_icon = (_tmp0_ = g_strdup (""), _g_free0 (self->priv->_icon), _tmp0_);
	}
	result = self->priv->_icon;
	return result;
}


void ui_widgets_abstract_tile_object_set_icon (UIWidgetsAbstractTileObject* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	if (_vala_strcmp0 (self->priv->_icon, value) == 0) {
		return;
	}
	if (ui_widgets_abstract_tile_object_get_force_pixbuf (self) != NULL) {
		ui_widgets_abstract_tile_object_set_force_pixbuf (self, NULL);
	}
	self->priv->_icon = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_icon), _tmp0_);
	g_signal_emit_by_name (self, "icon-updated");
	g_object_notify ((GObject *) self, "icon");
}


GdkPixbuf* ui_widgets_abstract_tile_object_get_force_pixbuf (UIWidgetsAbstractTileObject* self) {
	GdkPixbuf* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_force_pixbuf;
	return result;
}


void ui_widgets_abstract_tile_object_set_force_pixbuf (UIWidgetsAbstractTileObject* self, GdkPixbuf* value) {
	GdkPixbuf* _tmp0_;
	g_return_if_fail (self != NULL);
	if (self->priv->_force_pixbuf == value) {
		return;
	}
	self->priv->_force_pixbuf = (_tmp0_ = _g_object_ref0 (value), _g_object_unref0 (self->priv->_force_pixbuf), _tmp0_);
	g_signal_emit_by_name (self, "icon-updated");
	g_object_notify ((GObject *) self, "force-pixbuf");
}


const char* ui_widgets_abstract_tile_object_get_name (UIWidgetsAbstractTileObject* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	if (self->priv->_name == NULL) {
		char* _tmp0_;
		self->priv->_name = (_tmp0_ = g_strdup (""), _g_free0 (self->priv->_name), _tmp0_);
	}
	result = self->priv->_name;
	return result;
}


void ui_widgets_abstract_tile_object_set_name (UIWidgetsAbstractTileObject* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	if (_vala_strcmp0 (self->priv->_name, value) == 0) {
		return;
	}
	self->priv->_name = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_name), _tmp0_);
	g_signal_emit_by_name (self, "text-updated");
	g_object_notify ((GObject *) self, "name");
}


const char* ui_widgets_abstract_tile_object_get_description (UIWidgetsAbstractTileObject* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	if (self->priv->_description == NULL) {
		char* _tmp0_;
		self->priv->_description = (_tmp0_ = g_strdup (""), _g_free0 (self->priv->_description), _tmp0_);
	}
	result = self->priv->_description;
	return result;
}


void ui_widgets_abstract_tile_object_set_description (UIWidgetsAbstractTileObject* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	if (_vala_strcmp0 (self->priv->_description, value) == 0) {
		return;
	}
	self->priv->_description = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_description), _tmp0_);
	g_signal_emit_by_name (self, "text-updated");
	g_object_notify ((GObject *) self, "description");
}


const char* ui_widgets_abstract_tile_object_get_sub_description_title (UIWidgetsAbstractTileObject* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	if (self->priv->_subdesc_title == NULL) {
		char* _tmp0_;
		self->priv->_subdesc_title = (_tmp0_ = g_strdup (""), _g_free0 (self->priv->_subdesc_title), _tmp0_);
	}
	result = self->priv->_subdesc_title;
	return result;
}


void ui_widgets_abstract_tile_object_set_sub_description_title (UIWidgetsAbstractTileObject* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	if (_vala_strcmp0 (self->priv->_subdesc_title, value) == 0) {
		return;
	}
	self->priv->_subdesc_title = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_subdesc_title), _tmp0_);
	g_signal_emit_by_name (self, "text-updated");
	g_object_notify ((GObject *) self, "sub-description-title");
}


const char* ui_widgets_abstract_tile_object_get_sub_description_text (UIWidgetsAbstractTileObject* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	if (self->priv->_subdesc_text == NULL) {
		char* _tmp0_;
		self->priv->_subdesc_text = (_tmp0_ = g_strdup (""), _g_free0 (self->priv->_subdesc_text), _tmp0_);
	}
	result = self->priv->_subdesc_text;
	return result;
}


void ui_widgets_abstract_tile_object_set_sub_description_text (UIWidgetsAbstractTileObject* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	if (_vala_strcmp0 (self->priv->_subdesc_text, value) == 0) {
		return;
	}
	self->priv->_subdesc_text = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_subdesc_text), _tmp0_);
	g_signal_emit_by_name (self, "text-updated");
	g_object_notify ((GObject *) self, "sub-description-text");
}


gboolean ui_widgets_abstract_tile_object_get_show_action_button (UIWidgetsAbstractTileObject* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_show_action_button;
	return result;
}


void ui_widgets_abstract_tile_object_set_show_action_button (UIWidgetsAbstractTileObject* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->_show_action_button = value;
	g_object_notify ((GObject *) self, "show-action-button");
}


gboolean ui_widgets_abstract_tile_object_get_enabled (UIWidgetsAbstractTileObject* self) {
	gboolean result;
	g_return_val_if_fail (self != NULL, FALSE);
	result = self->priv->_enabled;
	return result;
}


void ui_widgets_abstract_tile_object_set_enabled (UIWidgetsAbstractTileObject* self, gboolean value) {
	g_return_if_fail (self != NULL);
	self->priv->_enabled = value;
	g_object_notify ((GObject *) self, "enabled");
}


const char* ui_widgets_abstract_tile_object_get_add_button_stock (UIWidgetsAbstractTileObject* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_add_button_stock;
	return result;
}


void ui_widgets_abstract_tile_object_set_add_button_stock (UIWidgetsAbstractTileObject* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_add_button_stock = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_add_button_stock), _tmp0_);
	g_object_notify ((GObject *) self, "add-button-stock");
}


const char* ui_widgets_abstract_tile_object_get_remove_button_stock (UIWidgetsAbstractTileObject* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_remove_button_stock;
	return result;
}


void ui_widgets_abstract_tile_object_set_remove_button_stock (UIWidgetsAbstractTileObject* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_remove_button_stock = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_remove_button_stock), _tmp0_);
	g_object_notify ((GObject *) self, "remove-button-stock");
}


const char* ui_widgets_abstract_tile_object_get_add_button_tooltip (UIWidgetsAbstractTileObject* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_add_button_tooltip;
	return result;
}


void ui_widgets_abstract_tile_object_set_add_button_tooltip (UIWidgetsAbstractTileObject* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_add_button_tooltip = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_add_button_tooltip), _tmp0_);
	g_object_notify ((GObject *) self, "add-button-tooltip");
}


const char* ui_widgets_abstract_tile_object_get_remove_button_tooltip (UIWidgetsAbstractTileObject* self) {
	const char* result;
	g_return_val_if_fail (self != NULL, NULL);
	result = self->priv->_remove_button_tooltip;
	return result;
}


void ui_widgets_abstract_tile_object_set_remove_button_tooltip (UIWidgetsAbstractTileObject* self, const char* value) {
	char* _tmp0_;
	g_return_if_fail (self != NULL);
	self->priv->_remove_button_tooltip = (_tmp0_ = g_strdup (value), _g_free0 (self->priv->_remove_button_tooltip), _tmp0_);
	g_object_notify ((GObject *) self, "remove-button-tooltip");
}


static void ui_widgets_abstract_tile_object_real_active_changed (UIWidgetsAbstractTileObject* self) {
	g_return_if_fail (self != NULL);
}


static void ui_widgets_abstract_tile_object_class_init (UIWidgetsAbstractTileObjectClass * klass) {
	ui_widgets_abstract_tile_object_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (UIWidgetsAbstractTileObjectPrivate));
	UI_WIDGETS_ABSTRACT_TILE_OBJECT_CLASS (klass)->active_changed = ui_widgets_abstract_tile_object_real_active_changed;
	G_OBJECT_CLASS (klass)->get_property = ui_widgets_abstract_tile_object_get_property;
	G_OBJECT_CLASS (klass)->set_property = ui_widgets_abstract_tile_object_set_property;
	G_OBJECT_CLASS (klass)->finalize = ui_widgets_abstract_tile_object_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), UI_WIDGETS_ABSTRACT_TILE_OBJECT_ICON, g_param_spec_string ("icon", "icon", "icon", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), UI_WIDGETS_ABSTRACT_TILE_OBJECT_FORCE_PIXBUF, g_param_spec_object ("force-pixbuf", "force-pixbuf", "force-pixbuf", GDK_TYPE_PIXBUF, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), UI_WIDGETS_ABSTRACT_TILE_OBJECT_NAME, g_param_spec_string ("name", "name", "name", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), UI_WIDGETS_ABSTRACT_TILE_OBJECT_DESCRIPTION, g_param_spec_string ("description", "description", "description", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), UI_WIDGETS_ABSTRACT_TILE_OBJECT_SUB_DESCRIPTION_TITLE, g_param_spec_string ("sub-description-title", "sub-description-title", "sub-description-title", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), UI_WIDGETS_ABSTRACT_TILE_OBJECT_SUB_DESCRIPTION_TEXT, g_param_spec_string ("sub-description-text", "sub-description-text", "sub-description-text", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), UI_WIDGETS_ABSTRACT_TILE_OBJECT_SHOW_ACTION_BUTTON, g_param_spec_boolean ("show-action-button", "show-action-button", "show-action-button", TRUE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), UI_WIDGETS_ABSTRACT_TILE_OBJECT_ENABLED, g_param_spec_boolean ("enabled", "enabled", "enabled", TRUE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), UI_WIDGETS_ABSTRACT_TILE_OBJECT_ADD_BUTTON_STOCK, g_param_spec_string ("add-button-stock", "add-button-stock", "add-button-stock", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), UI_WIDGETS_ABSTRACT_TILE_OBJECT_REMOVE_BUTTON_STOCK, g_param_spec_string ("remove-button-stock", "remove-button-stock", "remove-button-stock", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), UI_WIDGETS_ABSTRACT_TILE_OBJECT_ADD_BUTTON_TOOLTIP, g_param_spec_string ("add-button-tooltip", "add-button-tooltip", "add-button-tooltip", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), UI_WIDGETS_ABSTRACT_TILE_OBJECT_REMOVE_BUTTON_TOOLTIP, g_param_spec_string ("remove-button-tooltip", "remove-button-tooltip", "remove-button-tooltip", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_signal_new ("icon_updated", UI_WIDGETS_TYPE_ABSTRACT_TILE_OBJECT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("text_updated", UI_WIDGETS_TYPE_ABSTRACT_TILE_OBJECT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("buttons_updated", UI_WIDGETS_TYPE_ABSTRACT_TILE_OBJECT, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
	g_signal_new ("active_changed", UI_WIDGETS_TYPE_ABSTRACT_TILE_OBJECT, G_SIGNAL_RUN_LAST, G_STRUCT_OFFSET (UIWidgetsAbstractTileObjectClass, active_changed), NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void ui_widgets_abstract_tile_object_instance_init (UIWidgetsAbstractTileObject * self) {
	self->priv = UI_WIDGETS_ABSTRACT_TILE_OBJECT_GET_PRIVATE (self);
	self->priv->extra_buttons = NULL;
	self->priv->_show_action_button = TRUE;
	self->priv->_enabled = TRUE;
	self->priv->_add_button_stock = g_strdup (GTK_STOCK_ADD);
	self->priv->_remove_button_stock = g_strdup (GTK_STOCK_DELETE);
}


static void ui_widgets_abstract_tile_object_finalize (GObject* obj) {
	UIWidgetsAbstractTileObject * self;
	self = UI_WIDGETS_ABSTRACT_TILE_OBJECT (obj);
	__g_list_free_g_object_unref0 (self->priv->extra_buttons);
	_g_free0 (self->priv->_icon);
	_g_object_unref0 (self->priv->_force_pixbuf);
	_g_free0 (self->priv->_name);
	_g_free0 (self->priv->_description);
	_g_free0 (self->priv->_subdesc_title);
	_g_free0 (self->priv->_subdesc_text);
	_g_free0 (self->priv->_add_button_stock);
	_g_free0 (self->priv->_remove_button_stock);
	_g_free0 (self->priv->_add_button_tooltip);
	_g_free0 (self->priv->_remove_button_tooltip);
	G_OBJECT_CLASS (ui_widgets_abstract_tile_object_parent_class)->finalize (obj);
}


GType ui_widgets_abstract_tile_object_get_type (void) {
	static volatile gsize ui_widgets_abstract_tile_object_type_id__volatile = 0;
	if (g_once_init_enter (&ui_widgets_abstract_tile_object_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (UIWidgetsAbstractTileObjectClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) ui_widgets_abstract_tile_object_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (UIWidgetsAbstractTileObject), 0, (GInstanceInitFunc) ui_widgets_abstract_tile_object_instance_init, NULL };
		GType ui_widgets_abstract_tile_object_type_id;
		ui_widgets_abstract_tile_object_type_id = g_type_register_static (G_TYPE_OBJECT, "UIWidgetsAbstractTileObject", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
		g_once_init_leave (&ui_widgets_abstract_tile_object_type_id__volatile, ui_widgets_abstract_tile_object_type_id);
	}
	return ui_widgets_abstract_tile_object_type_id__volatile;
}


static void ui_widgets_abstract_tile_object_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	UIWidgetsAbstractTileObject * self;
	self = UI_WIDGETS_ABSTRACT_TILE_OBJECT (object);
	switch (property_id) {
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_ICON:
		g_value_set_string (value, ui_widgets_abstract_tile_object_get_icon (self));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_FORCE_PIXBUF:
		g_value_set_object (value, ui_widgets_abstract_tile_object_get_force_pixbuf (self));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_NAME:
		g_value_set_string (value, ui_widgets_abstract_tile_object_get_name (self));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_DESCRIPTION:
		g_value_set_string (value, ui_widgets_abstract_tile_object_get_description (self));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_SUB_DESCRIPTION_TITLE:
		g_value_set_string (value, ui_widgets_abstract_tile_object_get_sub_description_title (self));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_SUB_DESCRIPTION_TEXT:
		g_value_set_string (value, ui_widgets_abstract_tile_object_get_sub_description_text (self));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_SHOW_ACTION_BUTTON:
		g_value_set_boolean (value, ui_widgets_abstract_tile_object_get_show_action_button (self));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_ENABLED:
		g_value_set_boolean (value, ui_widgets_abstract_tile_object_get_enabled (self));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_ADD_BUTTON_STOCK:
		g_value_set_string (value, ui_widgets_abstract_tile_object_get_add_button_stock (self));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_REMOVE_BUTTON_STOCK:
		g_value_set_string (value, ui_widgets_abstract_tile_object_get_remove_button_stock (self));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_ADD_BUTTON_TOOLTIP:
		g_value_set_string (value, ui_widgets_abstract_tile_object_get_add_button_tooltip (self));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_REMOVE_BUTTON_TOOLTIP:
		g_value_set_string (value, ui_widgets_abstract_tile_object_get_remove_button_tooltip (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void ui_widgets_abstract_tile_object_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	UIWidgetsAbstractTileObject * self;
	self = UI_WIDGETS_ABSTRACT_TILE_OBJECT (object);
	switch (property_id) {
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_ICON:
		ui_widgets_abstract_tile_object_set_icon (self, g_value_get_string (value));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_FORCE_PIXBUF:
		ui_widgets_abstract_tile_object_set_force_pixbuf (self, g_value_get_object (value));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_NAME:
		ui_widgets_abstract_tile_object_set_name (self, g_value_get_string (value));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_DESCRIPTION:
		ui_widgets_abstract_tile_object_set_description (self, g_value_get_string (value));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_SUB_DESCRIPTION_TITLE:
		ui_widgets_abstract_tile_object_set_sub_description_title (self, g_value_get_string (value));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_SUB_DESCRIPTION_TEXT:
		ui_widgets_abstract_tile_object_set_sub_description_text (self, g_value_get_string (value));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_SHOW_ACTION_BUTTON:
		ui_widgets_abstract_tile_object_set_show_action_button (self, g_value_get_boolean (value));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_ENABLED:
		ui_widgets_abstract_tile_object_set_enabled (self, g_value_get_boolean (value));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_ADD_BUTTON_STOCK:
		ui_widgets_abstract_tile_object_set_add_button_stock (self, g_value_get_string (value));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_REMOVE_BUTTON_STOCK:
		ui_widgets_abstract_tile_object_set_remove_button_stock (self, g_value_get_string (value));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_ADD_BUTTON_TOOLTIP:
		ui_widgets_abstract_tile_object_set_add_button_tooltip (self, g_value_get_string (value));
		break;
		case UI_WIDGETS_ABSTRACT_TILE_OBJECT_REMOVE_BUTTON_TOOLTIP:
		ui_widgets_abstract_tile_object_set_remove_button_tooltip (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static int _vala_strcmp0 (const char * str1, const char * str2) {
	if (str1 == NULL) {
		return -(str1 != str2);
	}
	if (str2 == NULL) {
		return str1 != str2;
	}
	return strcmp (str1, str2);
}




